version: '3'

services:
  sonarqube-server:
    container_name: sonarqube-server
    image: sonarqube:7.9.1-community
    restart: always
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
      # Settings for nginx reverse proxy.
      - VIRTUAL_HOST=${SONARQUBE_DOMAIN}
      - VIRTUAL_PORT=9000
      # Settings for Let's Encrypt.
      - LETSENCRYPT_HOST=${SONARQUBE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
    depends_on:
      - sonarqube-db
    networks:
      - sonarqube

  sonarqube-db:
    container_name: sonarqube-db
    image: postgres:12.1
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql-root:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - sonarqube

  sonarqube-reverse-proxy:
    container_name: sonarqube-reverse-proxy
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    depends_on:
      - sonarqube-server
    networks:
      - sonarqube

  sonarqube-lets-encrypt:
    container_name: sonarqube-lets-encrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    environment:
      # Find nginx proxy container.
      - NGINX_PROXY_CONTAINER=sonarqube-reverse-proxy
      - NGINX_DOCKER_GEN_CONTAINER=sonarqube-reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    depends_on:
      - sonarqube-reverse-proxy
    networks:
      - sonarqube

networks:
  sonarqube:
    driver: bridge

volumes:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  postgresql-root:
  postgresql-data:
  nginx-certs:
  nginx-vhost:
  nginx-html:
